frontend:
  image: "hamsa/yolo-client"
  build_context: "./client"  # Path to your client directory
  dockerfile: "HamsaDockerfile"  # The Dockerfile name, assuming it's not the default 'Dockerfile'
  image_tag: "v1.0.0"  # Specify a tag if needed, e.g. 'v1.0.0'
