frontend:
  image: "hamsahassan/yolo-client:1.0"
  build_context: "./client"  # Path to your client directory
  dockerfile: "HamsaDockerfile"  # Dockerfile for frontend
  port: "3000"  # Port used by frontend
  container_name: "hamsa-client"
  image_tag: "v1.0.0"
  network: hamsa-net  # Network for communication with backend and mongo
