version: '3.8'

services:
  hamsa-client:
    build:
      context: ./client  # Path to your client directory
      dockerfile: HamsaDockerfile  # Correct Dockerfile name
    image: hamsahassan/yolo-client:v1.0.0
    container_name: hamsa-client
    ports:
      - "3000:3000"  # Maps port 3000 locally to container port 3000
    depends_on:
      - hamsa-backend
    networks:
      - hamsa-net
    stdin_open: true
    tty: true  # Keeps the container running for debugging

  hamsa-backend:
    build:
      context: ./backend  # Path to your backend directory
    image: hamsahassan/yolo-backend:v1.0.0
    container_name: hamsa-backend
    ports:
      - "5000:5000"
    depends_on:
      - hamsa-mongo
    environment:
      - MONGODB_URI=mongodb://hamsa-mongo:27017/yolomy
    networks:
      - hamsa-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

  hamsa-mongo:
    image: mongo:latest
    container_name: hamsa-mongo
    ports:
      - "27017:27017"
    networks:
      - hamsa-net

networks:
  hamsa-net:
    driver: bridge
