---
- name: Deploy YOLO E-Commerce Application Using Docker
  hosts: myserver
  become: true
  vars:
    frontend:
      container_name: hamsa-client
      image: hamsahassan/yolo-client:1.0  # Update this with the correct image name
      port: 3000
    backend:
      container_name: hamsa-backend
      image: hamsahassan/yolo-backend:1.0  # Update this with the correct image name
      port: 5000
      mongodb_uri: mongodb://hamsa-mongo:27017/yolomy
    mongodb:
      container_name: hamsa-mongo
      image: mongo:latest
      port: 27017
      network: hamsa-net

  tasks:

    # Clone the YOLO repository from GitHub
    - name: Clone the YOLO repository from GitHub
      git:
        repo: 'https://github.com/Ramayan0/yolo.git'
        dest: /home/hamsa/yolo

    # Debug MongoDB variables
    - name: Debug MongoDB variables
      debug:
        msg: "MongoDB Container Name: {{ mongodb.container_name }}, Image: {{ mongodb.image }}, Port: {{ mongodb.port }}, Network: {{ mongodb.network }}"

    # Debug Frontend variables
    - name: Debug Frontend variables
      debug:
        msg: "Frontend Container Name: {{ frontend.container_name }}, Image: {{ frontend.image }}, Port: {{ frontend.port }}"

    # Debug Backend variables
    - name: Debug Backend variables
      debug:
        msg: "Backend Container Name: {{ backend.container_name }}, Image: {{ backend.image }}, Port: {{ backend.port }}, MongoDB URI: {{ backend.mongodb_uri }}"

    # Create Docker network for the containers
    - name: Create Docker network for the containers
      docker_network:
        name: "{{ mongodb.network }}"
        driver: bridge

  roles:
    - frontend-deployment   # Role for Frontend setup
    - backend-deployment    # Role for Backend setup
    - setup-mongodb    # Role for MongoDB setup
