---
# Frontend Deployment Role - Deploy Frontend container

- name: Pull Frontend Docker image if it doesn't exist locally
  docker_image:
    name: "{{ frontend.image }}"
    source: pull
    tag: latest
  when: frontend.image not in lookup('pipe', 'docker images -q')

- name: Wait for Backend container to be ready
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ backend.port }}"
    state: started
    timeout: 60

- name: Create Frontend container
  docker_container:
    name: "{{ frontend.container_name }}"
    image: "{{ frontend.image }}"
    state: started
    restart_policy: unless-stopped
    exposed_ports:
      - "{{ frontend.port }}"
    published_ports:
      - "{{ frontend.port }}:{{ frontend.port }}"
    networks:
      - name: "{{ mongodb.network }}"
