- name: Build Docker image for frontend
  docker_image:
    name: "{{ frontend.image }}"  # specify the name of the image (e.g. 'hamsa/yolo-client')
    source: build  # this tells Ansible to build the image
    build:
      path: "{{ frontend.build_context }}"  # path to the Dockerfile context directory
      dockerfile: "{{ frontend.dockerfile }}"  # Dockerfile name if not default (Dockerfile)
    tag: "{{ frontend.image_tag }}"  # optional: specify a tag, e.g., 'v1.0.0'
  tags:
    - frontend
