
- name: Build Docker image for frontend
  docker_image:
    build:
      path: "{{ frontend.context }}"
      dockerfile: "{{ frontend.dockerfile }}"
    name: "{{ frontend.image }}"
    tag: latest
  tags:
    - frontend

- name: Run frontend Docker container
  docker_container:
    name: "{{ frontend.container_name }}"
    image: "{{ frontend.image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ frontend.port }}:{{ frontend.port }}"
    networks:
      - hamsa-net
  tags:
    - frontend
