
- name: Pull MongoDB Docker image
  docker_image:
    name: "{{ mongodb.image }}"
    source: pull
  tags:
    - mongodb

- name: Create MongoDB container
  docker_container:
    name: "{{ mongodb.container_name }}"
    image: "{{ mongodb.image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ mongodb.port }}:{{ mongodb.port }}"
    networks:
      - "{{ mongodb.network }}"
  tags:
    - mongodb
