---
- name: Set up MongoDB Docker container
  docker_container:
    name: hamsa-mongo
    image: mongo:latest
    state: started
    restart_policy: always
    published_ports:
      - "27017:27017"
    networks:
      - hamsa-net
  tags:
    - mongodb
