apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo
      tier: backend
  template:
    metadata:
      labels:
        app: yolo
        tier: backend
    spec:
      containers:
      - name: yolo-backend
        image: gcr.io/ip-4-orchestration/yolo-backend:v1.0.1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://34.171.63.71:27017"
        
