apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend-service
  labels:
    app: yolo
spec:
  selector:
    app: yolo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
