apiVersion: v1
kind: Service
metadata:
  name: hamsa-mongo-lb
  labels:
    app: yolo
spec:
  selector:
    app: yolo
    tier: backend
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer
