apiVersion: v1
kind: Service
metadata:
  name: hamsa-mongo
  labels:
    app: hamsa
spec:
  selector:
    app: hamsa
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
