apiVersion: v1
kind: Service
metadata:
  name: yolo-mongo
  labels:
    app: yolo
spec:
  selector:
    app: yolo
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
