---
# Backend Deployment Role - Deploy Backend container

- name: Pull Backend Docker image if it doesn't exist locally
  docker_image:
    name: "{{ backend.image }}"
    source: pull
    tag: latest
  when: backend.image not in lookup('pipe', 'docker images -q')

- name: Create Backend container
  docker_container:
    name: "{{ backend.container_name }}"
    image: "{{ backend.image }}"
    state: started
    restart_policy: unless-stopped
    exposed_ports:
      - "{{ backend.port }}"
    published_ports:
      - "{{ backend.port }}:{{ backend.port }}"
    environment:
      - MONGODB_URI={{ backend.mongodb_uri }}
    depends_on:
      - setup-mongodb
    networks:
      - name: "{{ mongodb.network }}"
