---
# Backend Deployment Role - Deploy Backend container

- name: Pull Backend Docker image if it doesn't exist locally
  docker_image:
    name: "{{ backend.image }}"
    source: pull
    tag: latest
  when: backend.image not in lookup('pipe', 'docker images -q')

- name: Create Backend container
  docker_container:
    name: "{{ backend.container_name }}"
    image: "{{ backend.image }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ backend.port }}:{{ backend.port }}"
    env:
      MONGODB_URI: "{{ backend.mongodb_uri }}"
    networks:
      - name: "{{ mongodb.network }}"
