# roles/backend-deployment/tasks/main.yml

- name: Build Docker image for backend
  docker_image:
    build:
      path: "{{ backend.context }}"
      dockerfile: "{{ backend.dockerfile }}"
    name: "{{ backend.image }}"
    tag: latest
  tags:
    - backend

- name: Run backend Docker container
  docker_container:
    name: "{{ backend.container_name }}"
    image: "{{ backend.image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ backend.port }}:{{ backend.port }}"
    environment:
      MONGODB_URI: "{{ backend.mongodb_uri }}"
    depends_on:
      - hamsa-mongo
    networks:
      - hamsa-net
  tags:
    - backend
