---
- name: Build and run backend Docker container
  docker_container:
    name: hamsa-backend
    image: hamsa/yolo-backend:v1.0.0
    state: started
    restart_policy: always
    published_ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb://hamsa-mongo:27017/yolomy"
    depends_on:
      - hamsa-mongo
    networks:
      - hamsa-net
  tags:
    - backend

- name: Build Docker image for backend
  docker_image:
    build:
      path: /vagrant/backend
      dockerfile: Dockerfile
    name: hamsa/yolo-backend:v1.0.0
    tag: latest
  tags:
    - backend
